### ISSUE TITLE
CLI feature: list available and installed JDKs

### ISSUE THREAD

**Issue by marktsuchida** [cachedjdk/cjdk#2]
Maybe `cjdk ls` and `cjdk ls --installed`.

**Comment by marktsuchida** [comment]
Also should have a way to list cached non-JDK files and packages.

**Comment by ctrueden** [comment]
> Also should have a way to list cached non-JDK files and packages.

See https://github.com/cachedjdk/cjdk/issues/6#issuecomment-1406655247
